name: Build & Release Wings for Oracle Linux
on:
  push:
    paths:
      - 'releases.json'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:8
    steps:
         - name: Build release
           id: build_release
           run: |
             curl -LO https://go.dev/dl/go1.18.7.linux-amd64.tar.gz
             tar -C /usr/local -xzf go1.18.7.linux-amd64.tar.gz
             export GOROOT=/usr/local/go
             export GOPATH=$HOME/go
             export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
             source ~/.bashrc
             go version
             dnf install -y jq wget unzip
             wget https://raw.githubusercontent.com/Kas-tle/wings-oci/main/releases.json
             VERSION=$(jq -r '.[-1]' releases.json)
             echo "::set-output name=VERSION::${VERSION}"
             echo -ne "$(curl -sL https://api.github.com/repos/pterodactyl/wings/releases/tags/${VERSION} | jq -r .body)" | head -n -5 > changelog.md
             wget https://github.com/pterodactyl/wings/archive/refs/tags/${VERSION}.zip
             unzip ${VERSION}.zip
             cd $(ls -d */|head -n 1)
             CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X github.com/pterodactyl/wings/system.Version=${VERSION#?}" -o ../wings_oracle_linux_amd64 -v wings.go
             CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X github.com/pterodactyl/wings/system.Version=${VERSION#?}" -o ../wings_oracle_linux_arm64 -v wings.go
             cd ..
             echo '```' >> changelog.md
             sha256sum wings_oracle_linux_amd64 >> changelog.md
             sha256sum wings_oracle_linux_arm64 >> changelog.md
             echo '```' >> changelog.md
         - name: Create tag
           uses: mathieudutour/github-tag-action@v5.5
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             tag_prefix: ''
             custom_tag: ${{ steps.build_release.outputs.VERSION }}
         - name: Create release
           uses: ncipollo/release-action@v1
           with:
             artifacts: "wings_oracle_linux_amd64,wings_oracle_linux_arm64"
             allowUpdates: true
             bodyFile: "changelog.md"
             draft: false
             prerelease: false
             tag: ${{ steps.build_release.outputs.VERSION }}
             token: ${{ secrets.GITHUB_TOKEN }}
